global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-monitoring'
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['31.97.61.2:8085']